import java.math.*;
import java.security.*;
import java.util.*;;
public class md51 {
	public static String getMd5(String input)
	{
		try {
			MessageDigest md = MessageDigest.getInstance("MD5");//use SHA-1 for sha insted 
			byte[] messageDigest = md.digest(input.getBytes());
			BigInteger no = new BigInteger(1, messageDigest);
			String hashtext = no.toString(16);
			while (hashtext.length() < 32) {
				hashtext = "0" + hashtext;
			}
			return hashtext;
		}
		catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(e);
		}
	}

	public static void main(String args[]) throws NoSuchAlgorithmException
	{
		String s;
		Scanner sc=new Scanner(System.in);
		System.out.print("enter msg: ");
		s=sc.nextLine();
		System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
		sc.close();
	}
}
